name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: Windows-latest
    name: Tests on chrome
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2 
      - name: install dependencies
        run: npm i
      - name: Run tests
        run: npm run runtest
      - name: Generate report
        run: npm run runrep
      - name: Upload artifact cucumber-report
      - name: Upload report
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: ghpages
            publish_dir: reports/cucumber-htmlreport/
             
